Add `Soroban.RPC.Server` and network_passphrase configuration
kommitters/soroban.ex pull request #150
Opened 2024-03-06 17:17 UTC by miguelnietoa

## Description

Fixes #149 

This PR:
1. Add `Soroban.RPC.Server` struct and receive network_passphrase in `Contract` functions
2. Deprecate `extra_fee_rate` parameter which is not necessary due to the `addl_resources` parameter which will increase Soroban resource fee.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-03-06 23:17 UTC, L-Zuluaga requested changes
Just found some small details, apart from that Looks great! 🚀

2024-03-06 23:17 UTC, L-Zuluaga commented on lib/rpc/server.ex
> +  def new(url) when is_binary(url) do
```suggestion
  def new(url) when is_binary(url), do:
```

2024-03-07 01:12 UTC, miguelnietoa commented on lib/rpc.ex
> +  defp call_get_ledger_entries({:ok, ledger_key_base64}, server) do
I try to avoid using `, do:` syntax when there is one statement in the function body but it is too long to fit in a single line.

Same in line 70.

2024-03-07 02:08 UTC, L-Zuluaga approved these changes

2024-03-07 02:39 UTC, merged