Invoke Contract Function
kommitters/soroban.ex pull request #39
Opened 2023-05-08 20:02 UTC by Odraxs

## Description

Closes #23 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-05-08 20:39 UTC, juanhurtado10 requested changes

2023-05-08 20:39 UTC, juanhurtado10 commented on lib/contract/invoke_host_function.ex
> +  def invoke(
@Odraxs there is too much logic encapsulated in a single function. Try breaking it down into functional code chunks.

2023-05-08 20:39 UTC, juanhurtado10 commented on lib/contract/invoke_host_function.ex
> +    sequence_number = SequenceNumber.new(seq_num)
@Odraxs the use of a `with` clause will make your function response and error handling predictable.

2023-05-09 13:52 UTC, miguelnietoa requested changes

2023-05-09 13:52 UTC, miguelnietoa commented on lib/contract/invoke_host_function.ex
> +  defp covert_to_sc_val(function_args) do
Fix typo

2023-05-09 13:52 UTC, miguelnietoa commented on lib/contract/contract.ex
This file should be placed in `lib/`

2023-05-09 13:52 UTC, miguelnietoa commented on test/contract/contract_test.exs
> +defmodule Stellar.Horizon.Client.ContractCannedAccountRequests do
Please improve this module name, it should always start with `Canned...`

2023-05-09 13:52 UTC, miguelnietoa commented on test/contract/contract_test.exs
> +defmodule Soroban.RPC.ContractCannedClientImpl do
Same as above!

2023-05-09 14:04 UTC, juanhurtado10 commented on lib/contract/invoke_host_function.ex
> +      invoke_host_function_op
@Odraxs I mean .... 👇 

```elixir
contract_id
|> create_host_function_op(function_name, function_args)
|> simulate(source_account, sequence_number)
|> send_transaction(...)
```

2023-05-09 14:13 UTC, Odraxs commented on lib/contract/invoke_host_function.ex
> +      invoke_host_function_op
@juanhurtado10 then, how do I send the result of `create_host_function_op` to `send_transaction`?

![image](https://github.com/kommitters/soroban.ex/assets/62166813/4363ed22-c3bb-42c8-ac9c-a334fe61db96)

2023-05-09 14:23 UTC, juanhurtado10 approved these changes
LGTM 🚀

2023-05-09 14:28 UTC, miguelnietoa approved these changes
Well done, guys! 🚀

2023-05-09 14:30 UTC, miguelnietoa approved these changes

2023-05-09 14:30 UTC, merged